set echo on;
set linesize 1000;
set pagesize 1000;
set heading on;

--1
SELECT bnd_id AS bnd_I,bnd_name,bnd_fee AS "Band Fee" 
FROM BAND  
ORDER BY bnd_fee DESC ;

--2 
SELECT BAND.BND_NAME , VENUE.VEN_NAME,EVENT.EVT_DATE_TIME,EVENT.EVT_DURATION,BUSINESS_SPONSOR.BUS_NAME 
FROM BAND, VENUE,EVENT,BUSINESS_SPONSOR 
WHERE BAND.BND_ID=EVENT.EVT_BND_ID AND EVENT.EVT_VENUE_ID = VENUE.VEN_ID AND EVENT.EVT_BUS_ID = BUSINESS_SPONSOR.BUS_ID 
ORDER BY VENUE.VEN_NAME , EVENT.EVT_DATE_TIME;

--3
SELECT  VEN_NAME,T.cnt AS "No of Events" 
FROM VENUE V, (SELECT EVT_VENUE_ID,COUNT(EVT_NO) AS cnt FROM EVENT GROUP BY EVT_VENUE_ID) T 
WHERE T.EVT_VENUE_ID= V.VEN_ID AND T.cnt>1 ;

--4
SELECT * FROM  SXSW_STAFF 
WHERE STF_DOB BETWEEN '31-DEC-1945' AND '1-DEC-1980' 
ORDER BY STF_HIREDATE DESC; 

--5
SELECT ORD_ITEM,SUM(ORD_AMOUNT) AS "#Ordered",SUM(ORD_AMOUNT*ORD_UNITPRICE) AS "Total Sales" 
FROM ORDERS 
GROUP BY ORD_ITEM HAVING SUM(ORD_AMOUNT*ORD_UNITPRICE) >50000;


--6
SELECT BND_NAME 
FROM BAND 
WHERE BND_ID NOT IN (SELECT EVENT.EVT_BND_ID FROM EVENT);

--7. 
SELECT * 
FROM BAND 
WHERE BND_TYPE = 'Pop' AND (BND_CITY='London' OR BND_CITY='Houston');

--8.
SELECT B.BND_ID,B.BND_NAME,T.eventsch AS "# Events Scheduled" 
FROM BAND B,(SELECT EVT_BND_ID,count(EVT_NO) AS eventsch FROM EVENT GROUP BY EVT_BND_ID) T 
WHERE B.BND_ID=T.EVT_BND_ID 
ORDER BY B.BND_NAME;

--9.
SELECT MGR_MGRNO,MGR_FIRSTNAME,MGR_LASTNAME,NVL(T.cnt,0) AS "Bands Managed" 
FROM MANAGER M LEFT JOIN (SELECT BND_MGNO , count (BND_MGNO) AS cnt FROM BAND GROUP BY BND_MGNO) T ON T.BND_MGNO = M.MGR_MGRNO 
ORDER BY M.MGR_MGRNO;

--10.
-- WITHOUT FORMATTING
SELECT STF_TITLE, AVG(STF_SALARY) 
FROM SXSW_STAFF 
GROUP BY STF_TITLE;

-- WITH FORMATTING
SELECT STF_TITLE, to_char( AVG(STF_SALARY), '$9,999.99' ) AS "Average Salary" 
FROM SXSW_STAFF 
GROUP BY STF_TITLE;

--11 
SELECT MGR_LASTNAME, MGR_FIRSTNAME 
FROM MANAGER 
WHERE MGR_LASTNAME IN (SELECT MGR_LASTNAME FROM MANAGER GROUP BY MGR_LASTNAME having count(*) > 1);

--12.
SELECT V.VEN_NAME,E.EVT_DATE_TIME,E.EVT_DURATION 
FROM EVENT E RIGHT JOIN VENUE V ON E.EVT_VENUE_ID=V.VEN_ID 
ORDER BY V.VEN_NAME, E.EVT_DATE_TIME;

--13.
SELECT VEN_NAME,T.avg_eve_budg,T.max_eve_budg,T.min_eve_budg 
FROM VENUE V , (SELECT EVT_VENUE_ID,AVG(EVT_BUDGET) AS avg_eve_budg,MAX(EVT_BUDGET) AS max_eve_budg,MIN(EVT_BUDGET) AS min_eve_budg FROM EVENT GROUP BY EVT_VENUE_ID HAVING MAX(EVT_BUDGET) > 1000000) T 
WHERE T.EVT_VENUE_ID=V.VEN_ID;

--14.
SELECT * 
FROM MANAGER 
WHERE MGR_LASTNAME LIKE 'G%m';

--15.
SELECT * 
FROM SXSW_STAFF 
WHERE STF_DOB IS NULL AND (STF_TITLE ='Event Coordinator' OR STF_TITLE ='Event Supervisor');