set echo on;
set linesize 1000;
set pagesize 1000;
set heading on;


--1
SELECT VENUE.VEN_NAME,EVENT.EVT_DATE_TIME,SXSW_STAFF.STF_NAME,TO_CHAR(WORK_SCHEDULE.WS_START_TIME,'HH:MM AM') AS "Start Time",TO_CHAR(WORK_SCHEDULE.WS_END_TIME,'HH:MM AM') AS "End Time",WS_ROLE
FROM WORK_SCHEDULE,EVENT,SXSW_STAFF,DCMURPHY.VENUE
WHERE WORK_SCHEDULE.WS_EVT_NO= EVENT.EVT_NO AND SXSW_STAFF.STF_ID=WORK_SCHEDULE.WS_STF_ID AND EVENT.EVT_VENUE_ID = VENUE.VEN_ID
ORDER BY EVENT.EVT_NO,SXSW_STAFF.STF_NAME;


--2 
SELECT SXSW_STAFF.STF_NAME,ROUND((sysdate-SXSW_STAFF.STF_DOB)/365) AS Age_in_Years,ROUND(sysdate-SXSW_STAFF.STF_HIREDATE) AS "Days Employed" 
FROM SXSW_STAFF 
ORDER BY Age_in_Years DESC;


--3
SELECT BND_NAME,BND_FEE,BND_TYPE 
FROM BAND B1 
WHERE B1.BND_FEE > (SELECT AVG(BND_FEE) AS average FROM BAND B2 GROUP BY BND_TYPE HAVING B2.BND_TYPE=B1.BND_TYPE);


--4 
SELECT STF_ID,STF_NAME,STF_SALARY 
FROM SXSW_STAFF 
WHERE STF_SALARY >=(SELECT max(STF_SALARY) FROM SXSW_STAFF WHERE STF_ID IN (SELECT UNIQUE(WS_STF_ID) FROM WORK_SCHEDULE WHERE WS_ROLE !='Event Coordinatior'));


--5
-- following the @
SELECT STF_NAME,STF_EMAIL,LENGTH(STF_EMAIL) AS "Length of Email Address" , LENGTH(SUBSTR(STF_EMAIL,INSTR(STF_EMAIL,'@')+1)) AS "Characters Following the @"
FROM SXSW_STAFF 
ORDER BY LENGTH(STF_EMAIL) DESC;

-- preceding the @
SELECT STF_NAME,STF_EMAIL,LENGTH(STF_EMAIL) AS "Length of Email Address" , LENGTH(SUBSTR(STF_EMAIL,0,INSTR(STF_EMAIL,'@')-1)) AS "Characters preceding the @"
FROM SXSW_STAFF 
ORDER BY LENGTH(STF_EMAIL) DESC;


--6
SELECT (SUBSTR(STF_NAME,0,INSTR(STF_NAME,' ')))||(SUBSTR(STF_NAME,INSTR(STF_NAME,'.')-1,INSTR(STF_NAME,'.'))) ||(SUBSTR(STF_NAME,INSTR(STF_NAME,' '),(INSTR(STF_NAME,' ',1,2)-INSTR(STF_NAME,' ')))) AS "Name of Staff"  
FROM SXSW_STAFF;


--7. 
SELECT TO_CHAR(TO_DATE(EXTRACT(month FROM STF_DOB),'MM'),'MONTH') "Month",COUNT(STF_ID) "# Staff Born"
FROM SXSW_STAFF
GROUP BY EXTRACT(month FROM STF_DOB)
ORDER BY EXTRACT(month FROM STF_DOB);


--8.
SELECT STF_NAME,
CASE WHEN STF_PHONE IS NULL THEN 'No Phone Available' ELSE ('('||substr(STF_PHONE,0,3)||')'||substr(STF_PHONE,4,3)||'-'||substr(STF_PHONE,7,4))END AS "Phone Number"
FROM SXSW_STAFF;


--9.
SELECT * 
FROM BUSINESS_SPONSOR 
WHERE BUS_ID NOT IN (SELECT UNIQUE(EVT_BUS_ID) FROM EVENT);


--10.
SELECT VEN_NAME 
FROM VENDOR V , (SELECT ORD_VEN_NO,COUNT(ORD_EVT_NO) FROM ORDERS GROUP BY ORD_VEN_NO HAVING COUNT(ORD_EVT_NO)>= (SELECT COUNT(*) FROM EVENT)) T
WHERE T.ORD_VEN_NO=V.VEN_NO;