set echo on;
set linesize 1000;
set pagesize 1000;
set heading on;

--1
SELECT BND_NAME,NVL(cnt,0) AS "#Events" 
FROM (SELECT BND_NAME,T.cnt FROM BAND B LEFT JOIN (SELECT EVT_BND_ID,COUNT(EVT_NO) AS cnt  FROM EVENT GROUP BY EVT_BND_ID) T ON t.EVT_BND_ID = B.BND_ID
UNION 
SELECT BND_NAME,T.cnt 
FROM BAND B 
RIGHT JOIN (SELECT EVT_BND_ID,COUNT(EVT_NO) AS cnt  FROM EVENT GROUP BY EVT_BND_ID) T ON t.EVT_BND_ID = B.BND_ID);


--2 
SELECT B.BND_NAME,(B.BND_FEE*T.noOfEvents) AS "SUM(BND_FEE)"  
FROM BAND B,(SELECT EVT_BND_ID,COUNT(evt_no) AS noOfEvents FROM EVENT GROUP BY EVT_BND_ID) T 
WHERE b.BND_ID=T.EVT_BND_ID;


--3
SELECT  STF_NAME , STF_SALARY, ROUND(ABS(STF_SALARY - AVG(STF_SALARY) OVER ( ) ))AS "Computed Difference"
FROM SXSW_STAFF
ORDER BY STF_NAME;


--4 
SELECT VENUE.VEN_NAME,EVENT.EVT_DATE_TIME,SXSW_STAFF.STF_NAME,TO_CHAR(WORK_SCHEDULE.WS_START_TIME,'HH:MM AM') AS "Start Time",TO_CHAR(WORK_SCHEDULE.WS_END_TIME,'HH:MM AM') AS "End Time",WS_ROLE
FROM WORK_SCHEDULE,EVENT,SXSW_STAFF,DCMURPHY.VENUE
WHERE WORK_SCHEDULE.WS_EVT_NO= EVENT.EVT_NO AND SXSW_STAFF.STF_ID=WORK_SCHEDULE.WS_STF_ID AND EVENT.EVT_VENUE_ID = VENUE.VEN_ID AND EVENT.EVT_DATE_TIME < '19-Mar-2015' 
ORDER BY EVENT.EVT_NO,SXSW_STAFF.STF_NAME;


--5
SELECT BAND.BND_NAME,MANAGER.MGR_LASTNAME,EVENT.EVT_DATE_TIME,VENUE.VEN_NAME
FROM BAND, EVENT , VENUE , MANAGER
WHERE VENUE.VEN_ID=EVENT.EVT_VENUE_ID AND EVENT.EVT_BND_ID=BAND.BND_ID AND BAND.BND_MGNO=MANAGER.MGR_MGRNO AND VENUE.VEN_AGE_POLICY='21+';


--6
SELECT s2.STF_TITLE,(SELECT AVG(STF_SALARY) FROM SXSW_STAFF s1 WHERE s1.STF_TITLE=s2.STF_TITLE GROUP BY s1.STF_TITLE) AS "Average Salary Staff"
FROM SXSW_STAFF s2 
GROUP BY s2.STF_TITLE;


--7.
-- USING KEY WORD 'Assistant'
SELECT * 
FROM (SELECT STF_NAME,ROUND((SYSDATE-STF_DOB)/365) AS AGE FROM SXSW_STAFF WHERE STF_TITLE !='Assistant' ORDER BY AGE) 
WHERE ROWNUM=1;


-- USING KEY WORD 'Usher'
SELECT * 
FROM (SELECT STF_NAME,ROUND((SYSDATE-STF_DOB)/365) AS AGE FROM SXSW_STAFF WHERE STF_TITLE !='Usher' ORDER BY AGE) 
WHERE ROWNUM=1;


--8.  
SELECT MAX(AVG(STF_SALARY)) AS "Average" 
FROM SXSW_STAFF 
GROUP BY STF_TITLE;


--9.
SELECT STF_NAME, sys_connect_by_path(STF_NAME,'/') AS "Organizational Position"
FROM   SXSW_STAFF
START WITH SXSW_STAFF.STF_SUP_ID IS NULL
CONNECT BY PRIOR STF_ID = STF_SUP_ID
ORDER  SIBLINGS BY STF_NAME;


--10.
SELECT LPAD('  ', 3*LEVEL-1)||STF_NAME AS "Staff Name"
FROM   SXSW_STAFF
START WITH SXSW_STAFF.STF_SUP_ID IS NULL
CONNECT BY PRIOR STF_ID = STF_SUP_ID 
ORDER BY LEVEL;